# Generated by Django 3.0.5 on 2020-05-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='社团名称'),
        ),
    ]
