# Generated by Django 3.0.5 on 2020-07-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20200526_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='是否通过审核'),
        ),
    ]
