# Generated by Django 3.0.5 on 2020-07-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_membership_valid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'community'), name='user_community_unique'),
        ),
    ]
