# Generated by Django 3.0.5 on 2020-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20200713_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='社团是否通过审核'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='成员是否通过审核'),
        ),
    ]
