# Generated by Django 3.0.7 on 2020-08-05 05:28

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_community_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='checklist',
            field=django_mysql.models.JSONField(default=list, verbose_name='待办清单 JSON'),
        ),
    ]
