# Generated by Django 3.1 on 2020-08-18 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_auto_20200805_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='rec_link',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(message='请输入睿客网链接（以 http(s)://rec.ustc.edu.cn/ 开头）。', regex='http[s]?://rec.ustc.edu.cn/.+')], verbose_name='睿客网链接'),
        ),
    ]
