# Generated by Django 3.0.6 on 2020-06-07 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0002_auto_20200526_0627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知时间')),
                ('type', models.CharField(choices=[('PC', 'PersonalCommunalNotice'), ('AR', 'At/ReplyNotice'), ('CA', 'Create/ApplyNotice'), ('B', 'BanNotice'), ('C_AN', 'Community_ActivityNotice'), ('C_AP', 'Community_AdminPersonnelNotice'), ('C_AA', 'Community_AdminAuditNotice'), ('C_D', 'Community_DismissNotice'), ('S_CA', 'System_CommunityAuditNotice')], max_length=4, verbose_name='通知类型')),
                ('subtype', models.IntegerField(null=True, verbose_name='通知子类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='通知描述')),
                ('related_community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.Community', verbose_name='关联社团')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='已读')),
                ('deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.Notice', verbose_name='通知')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
