# Generated by Django 3.0.6 on 2020-06-07 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_auto_20200526_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知时间')),
                ('type', models.IntegerField(verbose_name='通知类型')),
                ('subtype', models.IntegerField(null=True, verbose_name='通知子类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='通知描述')),
                ('related_community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.Community', verbose_name='关联社团')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
        ),
    ]
