# Generated by Django 3.0.6 on 2020-06-09 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('notice', '0002_auto_20200608_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='related_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Comment', verbose_name='关联评论'),
        ),
    ]
