# Generated by Django 3.0.6 on 2020-08-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_related_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticebox',
            name='administrative',
            field=models.BooleanField(default=False, verbose_name='是否为管理员通知'),
        ),
    ]
