# Generated by Django 3.0.7 on 2020-08-07 07:03

import activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='secret_key',
            field=models.CharField(default=activity.models.random_secret_key, max_length=32, verbose_name='签到密钥'),
        ),
    ]
