# Generated by Django 3.0.5 on 2020-05-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='对 admin/ 管理页的只读权限', verbose_name='staff status'),
        ),
    ]
