# Generated by Django 3.0.5 on 2020-05-07 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200507_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visibility',
            name='email',
            field=models.CharField(choices=[('0', '公开'), ('1', '仅社团成员可见'), ('2', '仅管理员可见')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='visibility',
            name='phone',
            field=models.CharField(choices=[('0', '公开'), ('1', '仅社团成员可见'), ('2', '仅管理员可见')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='visibility',
            name='profile',
            field=models.CharField(choices=[('0', '公开'), ('1', '仅社团成员可见'), ('2', '仅管理员可见')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='visibility',
            name='real_name',
            field=models.CharField(choices=[('0', '公开'), ('1', '仅社团成员可见'), ('2', '仅管理员可见')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='visibility',
            name='student_id',
            field=models.CharField(choices=[('0', '公开'), ('1', '仅社团成员可见'), ('2', '仅管理员可见')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='visibility',
            name='user',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
