# Generated by Django 3.0.5 on 2020-05-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200507_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visibility',
        ),
    ]
