# Generated by Django 3.0.5 on 2020-07-28 05:44

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200728_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=account.models.user_avatar_path, verbose_name='头像'),
        ),
    ]
